### ISSUE TITLE
swat connection from Windows via Pycharm

### ISSUE THREAD

**Issue by IN92** [sassoftware/python-swat#56] opened 2019-10-07 15:30 UTC
Hi, 

When trying to connect to CAS, using the python SWAT package on a Windows machine having pycharm installed the following error occurs:
"The extensions for the binary protocol have not been installed.  You can either install them using the full platform-dependent install file, or use the REST interface as an alternative."

**Comment by IvanNardini** [comment] 2019-10-08 19:47
The issue is releated to the Python version of interpreter. I switch from Python 3.7.4 to Python 3.6.8 and it works.
I would like to suggest further investigations

**Comment by kesmit13** [comment] 2019-10-14 13:29
Could you run the following, then look in the `lib\win' subdirectory where the SWAT package resides and see what `py*swat.dll` files you have there?  There should be a `py37swat.dll` for Python 3.7 support.

```
import swat
print(swat.__file__) 
```

**Comment by kesmit13** [comment] 2019-11-06 15:28
I'm still not sure what's happening on your machine, but I double checked and Python 3.7 does work with the current version of SWAT on my Windows machine.
```
C:\Users\kesmit13>ipython
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import swat

In [2]: swat.__version__
Out[2]: '1.5.2'
```

**Comment by IN92** [comment] 2019-11-06 20:45
Hi Kevin,

sorry for delay.

If you think it may be useful, I try to reproduce the error and back to you
with detailed log.

Just let me know

Ivan

Il giorno mer 6 nov 2019 alle ore 16:28 Kevin D Smith <
notifications@github.com> ha scritto:

**Comment by kesmit13** [comment] 2019-11-06 22:24
I'd appreciate it if you could since I can't reproduce it.

**Comment by kesmit13** [comment] 2019-11-21 20:21
This turned out to be an issue of installing from the source distribution rather than the platform releases.  Closing.

**Closed by kesmit13** 2019-11-21 20:21 UTC
