### ISSUE TITLE
Error uploading a large dataframe

### ISSUE THREAD

**Issue by sahbic** [sassoftware/python-swat#69] opened 2020-03-18 09:56 UTC
Hello,

I have an error trying to upload a large dataframe using **upload_frame**
`s.upload_frame(df, casout={'caslib':'caslib_name', 'name':'table_name','promote':True})`

The error I get is:

> SWATError: string longer than 2147483647 bytes

[error.txt](https://github.com/sassoftware/python-swat/files/4349399/error.txt)

**Dataframe details:**
nrows = ~60 million
ncolumns = 22
size = ~7Gb

**Versions:**
swat: 1.6.1
pandas 0.24.2

**Comment by kesmit13** [comment] 2020-03-18 13:47
Can you post the full traceback?  Although, I will say for something that size, you'll be better off uploading it using another method such as scp / sftp / etc. then using the loadtable action to load it from the server side.

**Comment by sahbic** [comment] 2020-03-18 14:08
Please find the traceback file attached here [error.txt](https://github.com/sassoftware/python-swat/files/4349377/error.txt)
I have added it to the original post as well.

**Comment by kesmit13** [comment] 2020-03-18 15:06
I'm wondering if there is a size limit in the Python requests package, or maybe even in the CAS REST server (I'm checking into that).  I kind of wish that exception wasn't wrapped in a SWATError so I could see where it's really coming from; I might have to make that change in the code.  If you have access to the SWAT installation, you could try commenting out lines 597 & 598 in swat\cas\rest\connection.py and see if that gives better information.

**Comment by sahbic** [comment] 2020-03-20 17:07
Hi, I have commented out the lines. Please find attached the traceback here: [error.txt](https://github.com/sassoftware/python-swat/files/4360932/error.txt)

**Comment by kesmit13** [comment] 2020-03-20 18:05
That's interesting.  It appears as though the SSL library in Python won't allow sending data of more than 2GB.  I don't know if that's a hard-coded limit, or something that's configurable though.  I haven't been able to find any place this limitation is documented.

I think exporting the DataFrame to CSV, then uploading it using another means (scp/sftp/etc.) maybe the only solution here.

**Comment by kesmit13** [comment] 2020-07-15 20:48
Since I couldn't find a way around the limit in the SSL library in Python, I'm going to close this one.  If you happen to find any information about getting around this limitation, I can look into it again.

**Closed by kesmit13** 2020-07-15 20:48 UTC

**Comment by spgathade** [comment] 2024-05-30 13:21
@kesmit13 
In Python 3.10.11, I am getting this error while uploading large data frame larger than 2GB. I am using REST Connection


Error - 

SSLError                                  Traceback (most recent call last)
SSLError: EOF occurred in violation of protocol (_ssl.c:2426)

The above exception was the direct cause of the following exception:

MaxRetryError                             Traceback (most recent call last)
File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py:667, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    666 try:
--> 667     resp = conn.urlopen(
    668         method=request.method,
    669         url=url,
    670         body=request.body,
    671         headers=request.headers,
    672         redirect=False,
    673         assert_same_host=False,
    674         preload_content=False,
    675         decode_content=False,
    676         retries=self.max_retries,
    677         timeout=timeout,
    678         chunked=chunked,
    679     )
    681 except (ProtocolError, OSError) as err:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:847, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)
    845     new_e = ProtocolError("Connection aborted.", new_e)
--> 847 retries = retries.increment(
    848     method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    849 )
    850 retries.sleep()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py:515, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    514     reason = error or ResponseError(cause)
--> 515     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    517 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host='host', port=443): Max retries exceeded with url: /cas-shared-default-http/cas/sessions/8c691e32-6e0c-204a-94db-fd0263c7fa24/actions/table.upload (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\swat\cas\rest\connection.py:822, in REST_CASConnection.upload(self, file_name, params)
    820     _print_request('DELETE', url, self._req_sess.headers, data)
--> 822 res = self._req_sess.put(url, data=data)
    824 if get_option('cas.debug.responses'):

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py:649, in Session.put(self, url, data, **kwargs)
    640 r"""Sends a PUT request. Returns :class:`Response` object.
    641 
    642 :param url: URL for the new :class:`Request` object.
   (...)
    646 :rtype: requests.Response
    647 """
--> 649 return self.request("PUT", url, data=data, **kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py:589, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    588 send_kwargs.update(settings)
--> 589 resp = self.send(prep, **send_kwargs)
    591 return resp

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py:703, in Session.send(self, request, **kwargs)
    702 # Send the request
--> 703 r = adapter.send(request, **kwargs)
    705 # Total elapsed time of the request (approximately)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py:698, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    696 if isinstance(e.reason, _SSLError):
    697     # This branch is for urllib3 v1.22 and later.
--> 698     raise SSLError(e, request=request)
    700 raise ConnectionError(e, request=request)

SSLError: HTTPSConnectionPool(host='host', port=443): Max retries exceeded with url: /cas-shared-default-http/cas/sessions/8c691e32-6e0c-204a-94db-fd0263c7fa24/actions/table.upload (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')))

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\swat\cas\rest\connection.py:527, in REST_CASConnection._set_next_connection(self)
    526 try:
--> 527     self._current_hostname = self._hostname[self._host_index]
    528     self._current_baseurl = self._baseurl[self._host_index]

IndexError: list index out of range

During handling of the above exception, another exception occurred:

SWATError                                 Traceback (most recent call last)
Cell In[15], line 3
      1 # conn.copy()
----> 3 conn.upload_file('account.sas7bdat')

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\swat\cas\connection.py:1781, in CAS.upload_file(self, data, importoptions, casout, **kwargs)
   1778         casout = value
   1779         del kwargs[key]
-> 1781 out = self.upload(data, importoptions=importoptions,
   1782                   casout=casout, **kwargs)
   1784 if out.severity > 1:
   1785     raise SWATError(out.status)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\swat\cas\connection.py:1734, in CAS.upload(self, data, importoptions, casout, date_format, **kwargs)
   1731 kwargs['casout'] = casout
   1733 if isinstance(self._sw_connection, rest.REST_CASConnection):
-> 1734     resp = self._sw_connection.upload(a2n(filename), kwargs)
   1735 else:
   1736     resp = errorcheck(self._sw_connection.upload(a2n(filename),
   1737                                                  py2cas(self._soptions,
   1738                                                         self._sw_error,
   1739                                                         **kwargs)),
   1740                       self._sw_connection)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\swat\cas\rest\connection.py:831, in REST_CASConnection.upload(self, file_name, params)
    828     break
    830 except requests.ConnectionError:
--> 831     self._set_next_connection()
    833 except Exception as exc:
    834     raise SWATError(str(exc))

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\swat\cas\rest\connection.py:534, in REST_CASConnection._set_next_connection(self)
    532 self._current_baseurl = ''
    533 self._current_port = -1
--> 534 raise SWATError('Unable to connect to any URL in the list: %s' %
    535                 ', '.join(self._baseurl))

SWATError: Unable to connect to any URL in the list: [https://host:443/cas-shared-default-http/](https://host/cas-shared-default-http/)

**Comment by spgathade** [comment] 2024-06-03 10:08
@sahbic Have you got any solution to this issue?

**Comment by spgathade** [comment] 2024-06-03 10:11
@bkemper24 Can you please check the above logs?

**Comment by bkemper24** [comment] 2024-06-13 14:49
@spgathade 

I've been looking through your logs and I'm not sure exactly what is causing your problem.  But here is what I see when I try it :
If I try to upload a data frame around the size of Content-Length: 2517115513 , I get an error response from nginx indicating that the upload is too big :

<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

If I increase the size of the data frame to a little larger, instead of the 413 response, I get the exception that you are seeing, SSLError: EOF occurred in violation of protocol 

By contrast, if I instead connect to cas over https using the http NodePort I am able to successfully upload both the dataframe that caused the 413 response and the larger dataframe that caused the SSLError.

So I believe that you are running into some sort of size limitation from the ingress.
