### ISSUE TITLE
Issues with the round method on SASDataFrame objects

### ISSUE THREAD

**Issue by pestyld** [sassoftware/python-swat#141] opened 2022-11-09 13:10 UTC
There seems to be an issue with the round method on a SASDataFrame object. 

For example, i'll load the following file as a CAS Table

`castbl = conn.read_csv(r'https://support.sas.com/documentation/onlinedoc/viya/exampledatasets/cars.csv',  casout = {'name':'hmeq',                                                          
                                 'caslib':'casuser', 
                                 'replace':True})`

Then i'll execute the describe and round methods on the CASTable objects. The describe method returns a SASDataFrame, and the round method should round that DataFrame.

`castbl.describe().round()`
The results show it makes all the values NaN
![Round Describe](https://user-images.githubusercontent.com/58962057/200837881-db04b4d1-9267-4d06-b350-1155840578f5.png)

I also tested this with the head method on a CASTable object. I get this error:
`castbl.head().round()`
![Error](https://user-images.githubusercontent.com/58962057/200838196-4c1a85fb-401b-4b79-885c-6db6f96fa85c.png)

If you use traditional Pandas and create a traditional DataFrame, the round method works each time.

`df = pd.read_csv(r'https://support.sas.com/documentation/onlinedoc/viya/exampledatasets/cars.csv')`
`df.describe().round()`
`df.head().round()`

![dataframeround](https://user-images.githubusercontent.com/58962057/200838527-3f05d9f2-a71a-4a0d-bfcb-bfa7d5416dc1.png)

**Comment by bkemper24** [comment] 2023-05-10 12:11
This appears to be a problem with pandas.  The problem was introduced in pandas version 1.2.0.
The problem occurs when a class that subclasses pandas.DataFrame ( in this case the SASDataFrame class ) contains an original property named "name" that is included in the _metadata list.

The problem is fixed in pandas version 2.0.0 that was released last month.

**Closed** 2023-06-08 14:59 UTC
